export const interests = {
  reading: "Reading",
  writing: "Writing",
  cooking: "Cooking",
  baking: "Baking",
  painting: "Painting",
  drawing: "Drawing",
  photography: "Photography",
  gardening: "Gardening",
  knitting: "Knitting",
  crocheting: "Crocheting",
  sewing: "Sewing",
  woodworking: "Woodworking",
  metalworking: "Metalworking",
  pottery: "Pottery",
  sculpting: "Sculpting",
  dancing: "Dancing",
  singing: "Singing",
  "playing-musical-instruments": "Playing Musical Instruments",
  "listening-to-music": "Listening to Music",
  "watching-movies": "Watching Movies",
  theater: "Theater",
  opera: "Opera",
  ballet: "Ballet",
  "stand-up-comedy": "Stand-Up Comedy",
  "magic-and-illusion": "Magic and Illusion",
  "bird-watching": "Bird Watching",
  astronomy: "Astronomy",
  "stamp-collecting": "Stamp Collecting",
  "coin-collecting": "Coin Collecting",
  "antique-collecting": "Antique Collecting",
  "car-collecting": "Car Collecting",
  "model-building": "Model Building",
  "puzzle-solving": "Puzzle Solving",
  "board-games": "Board Games",
  "card-games": "Card Games",
  "video-gaming": "Video Gaming",
  "role-playing-games": "Role-Playing Games",
  chess: "Chess",
  yoga: "Yoga",
  meditation: "Meditation",
  "fitness-and-gym": "Fitness and Gym",
  running: "Running",
  cycling: "Cycling",
  hiking: "Hiking",
  backpacking: "Backpacking",
  camping: "Camping",
  "rock-climbing": "Rock Climbing",
  mountaineering: "Mountaineering",
  skiing: "Skiing",
  snowboarding: "Snowboarding",
  surfing: "Surfing",
  "scuba-diving": "Scuba Diving",
  snorkeling: "Snorkeling",
  fishing: "Fishing",
  kayaking: "Kayaking",
  canoeing: "Canoeing",
  sailing: "Sailing",
  windsurfing: "Windsurfing",
  "kite-surfing": "Kite Surfing",
  paragliding: "Paragliding",
  skydiving: "Skydiving",
  "bungee-jumping": "Bungee Jumping",
  "martial-arts": "Martial Arts",
  boxing: "Boxing",
  wrestling: "Wrestling",
  archery: "Archery",
  "shooting-sports": "Shooting Sports",
  "horseback-riding": "Horseback Riding",
  golf: "Golf",
  tennis: "Tennis",
  badminton: "Badminton",
  "table-tennis": "Table Tennis",
  soccer: "Soccer",
  football: "Football",
  basketball: "Basketball",
  baseball: "Baseball",
  volleyball: "Volleyball",
  cricket: "Cricket",
  rugby: "Rugby",
  "ice-hockey": "Ice Hockey",
  "field-hockey": "Field Hockey",
  swimming: "Swimming",
  traveling: "Traveling",
  "backyard-astronomy": "Backyard Astronomy",
  "urban-exploration": "Urban Exploration",
  geocaching: "Geocaching",
  "wine-tasting": "Wine Tasting",
  "brewing-beer": "Brewing Beer",
  "distilling-spirits": "Distilling Spirits",
  "cheese-making": "Cheese Making",
  "home-renovation": "Home Renovation",
  "diy-projects": "DIY Projects",
  "animal-care": "Animal Care",
  volunteering: "Volunteering",
  "language-learning": "Language Learning",
  calligraphy: "Calligraphy",
  blogging: "Blogging",
  podcasting: "Podcasting",
  vlogging: "Vlogging",
  collecting: "Collecting",
};
