/* convert this array to JSON object where the keys are a computer friendly version of the name (i.e. communication-studies) and values are human readable format (i.e. Communication Studies): 
  "Accounting",
  "Architecture",
  "Art",
  "Asian Studies",
  "Behavioral Neuroscience",
  "Biochemistry",
  "Biology",
  "Biology, Marine",
  "Business Administration",
  "Chemistry",
  "Communication Studies",
  "Computer Science",
  "Criminal Justice",
  "Economics",
  "Education",
  "Engineering",
  "English",
  "Entrepreneurship and Innovation",
  "Environmental Geology ",
  "Environmental Science",
  "Environmental Studies",
  "Game Design",
  "Geology",
  "Design",
  "Health Science",
  "History",
  "Human Services",
  "Information Science",
  "International Affairs",
  "International Business",
  "Jewish Studies",
  "Journalism",
  "Languages, Literatures, and Cultures",
  "Languages, Spanish",
  "Linguistics",
  "Management",
  "Management Information Systems",
  "Marketing",
  "Mathematics",
  "Media and Screen Studies",
  "Media Arts",
  "Music",
  "Nursing",
  "Pharmaceutical Sciences",
  "Pharmacy",
  "Philosophy",
  "Physical Therapy",
  "Physics",
  "Physics, Biomedical",
  "Political Science",
  "Psychology",
  "Rehabilitation Studies",
  "Religious Studies",
  "Sign Language, American",
  "Sociology",
  "Studio Art",
  "Supply Chain Management",
  "Theatre",
 */

export const majors = {
  accounting: "Accounting",
  architecture: "Architecture",
  art: "Art",
  "asian-studies": "Asian Studies",
  "behavioral-neuroscience": "Behavioral Neuroscience",
  biochemistry: "Biochemistry",
  biology: "Biology",
  "biology-marine": "Biology, Marine",
  "business-administration": "Business Administration",
  chemistry: "Chemistry",
  "communication-studies": "Communication Studies",
  "computer-science": "Computer Science",
  "criminal-justice": "Criminal Justice",
  economics: "Economics",
  education: "Education",
  engineering: "Engineering",
  english: "English",
  "entrepreneurship-and-innovation": "Entrepreneurship and Innovation",
  "environmental-geology": "Environmental Geology ",
  "environmental-science": "Environmental Science",
  "environmental-studies": "Environmental Studies",
  "game-design": "Game Design",
  geology: "Geology",
  design: "Design",
  "health-science": "Health Science",
  history: "History",
  "human-services": "Human Services",
  "information-science": "Information Science",
  "international-affairs": "International Affairs",
  "international-business": "International Business",
  "jewish-studies": "Jewish Studies",
  journalism: "Journalism",
  "languages-literatures-and-cultures": "Languages, Literatures, and Cultures",
  "languages-spanish": "Languages, Spanish",
  linguistics: "Linguistics",
  management: "Management",
  "management-information-systems": "Management Information Systems",
  marketing: "Marketing",
  mathematics: "Mathematics",
  "media-and-screen-studies": "Media and Screen Studies",
  "media-arts": "Media Arts",
  music: "Music",
  nursing: "Nursing",
  "pharmaceutical-sciences": "Pharmaceutical Sciences",
  pharmacy: "Pharmacy",
  philosophy: "Philosophy",
  "physical-therapy": "Physical Therapy",
  physics: "Physics",
  "physics-biomedical": "Physics, Biomedical",
  "political-science": "Political Science",
  psychology: "Psychology",
  "rehabilitation-studies": "Rehabilitation Studies",
  "religious-studies": "Religious Studies",
  "sign-language-american": "Sign Language, American",
  sociology: "Sociology",
  "studio-art": "Studio Art",
  "supply-chain-management": "Supply Chain Management",
  theatre: "Theatre",
};
