export const baCodes = [
  { label: "01 - Basic Research", value: "1" },
  { label: "02 - Applied Research", value: "2" },
  { label: "03 - Advanced Technology Development", value: "3" },
  { label: "04 - Advanced Component Development and Prototypes", value: "4" },
  { label: "05 - System Development and Demonstration", value: "5" },
  { label: "06 - RDT&E Management Support", value: "6" },
  { label: "07 - Operational Systems Development", value: "7" },
  { label: "08 - Engineering and Manufacturing Development", value: "8" },
  { label: "09 - Test and Evaluation", value: "9" },
  { label: "10 - Management Support", value: "10" },
  { label: "11 - Operational Systems Development", value: "11" },
  { label: "12 - RDT&E Management Support", value: "12" },
  { label: "13 - Operational Systems Development", value: "13" },
  { label: "14 - Other", value: "14" },
];
